/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gtnewhorizons.retrofuturagradle;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A plugin for modding 1.7.10 Minecraft
 */
public class RetroFuturaGradlePlugin implements Plugin<Project> {
    public void apply(Project project) {


        // Register a task
        project.getTasks().register("greeting", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'com.gtnewhorizons.retrofuturagradle.greeting'"));
        });
    }
}
