/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gtnewhorizons.retrofuturagradle;

import com.gtnewhorizons.retrofuturagradle.minecraft.MinecraftTasks;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A plugin for modding 1.7.10 Minecraft
 */
public class RetroFuturaGradlePlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register the `minecraft {...}` block
        final MinecraftExtension mcExt = project.getExtensions().create("minecraft", MinecraftExtension.class);

        final MinecraftTasks mcTasks = new MinecraftTasks(project, mcExt);
    }
}
