/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6/userguide/multi_project_builds.html
 */

rootProject.name = "RetroFuturaGradleTestMods"
pluginManagement {
    includeBuild("plugin") {
        name = "retrofuturagradle"
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
}

include("testmod")
include("testmod1.12")
include("testdepmod")
